export type EvidenceLevel = 'strong' | 'moderate' | 'emerging';

export interface Citation {
  authors: string;
  year: number;
  title: string;
  journal: string;
  doi: string;
}

export interface Evidence {
  id: string;
  technique: string;
  category: 'breath' | 'nervous_system' | 'mind' | 'cycle' | 'recovery';
  claim: string;
  evidenceLevel: EvidenceLevel;
  citation: Citation;
  mechanism: string;
  effectSize: string;
}

export const EVIDENCE: readonly Evidence[] = Object.freeze([
  {
    id: 'breathing-4-7-8',
    technique: '4-7-8 breathing',
    category: 'breath',
    claim:
      'Inhale 4, hold 7, exhale 8 — extended exhalation increases vagal tone and shifts toward parasympathetic dominance.',
    evidenceLevel: 'moderate',
    citation: {
      authors: 'Vierra J, Boonla O, Prasertsri P',
      year: 2022,
      title:
        'Effects of sleep deprivation and 4-7-8 breathing control on heart rate variability, blood pressure, blood glucose, and endothelial function in healthy young adults',
      journal: 'Physiological Reports, 10(13), e15389',
      doi: 'https://doi.org/10.14814/phy2.15389',
    },
    mechanism:
      'Prolonged exhalation recruits parasympathetic outflow via vagal afferents, increasing high-frequency HRV power and reducing systolic blood pressure.',
    effectSize:
      'In rested adults (n = 43), one 4-7-8 session (3 sets × 6 cycles) significantly increased normalised HF-HRV and reduced systolic BP from 109 → 105 mmHg (p < 0.001).',
  },
  {
    id: 'resonant-breathing-6bpm',
    technique: 'Resonant breathing (~6 breaths/min)',
    category: 'breath',
    claim:
      'Breathing at ~6 cycles per minute maximises heart rate variability and synchronises cardiovascular oscillations.',
    evidenceLevel: 'strong',
    citation: {
      authors: 'Bernardi L, Sleight P, Bandinelli G et al.',
      year: 2001,
      title:
        'Effect of rosary prayer and yoga mantras on autonomic cardiovascular rhythms: comparative study',
      journal: 'BMJ, 323(7327), 1446–1449',
      doi: 'https://doi.org/10.1136/bmj.323.7327.1446',
    },
    mechanism:
      'Breathing at ~6/min synchronises respiratory and cardiovascular oscillations at the 0.1 Hz baroreflex resonance frequency, maximising baroreflex sensitivity and vagal HRV.',
    effectSize:
      'Both rosary prayer and yoga mantra slowed respiration to ~6/min and produced "striking, powerful, and synchronous" increases in HRV and baroreflex sensitivity vs spontaneous breathing (n = 23).',
  },
  {
    id: 'physiological-sigh',
    technique: 'Cyclic sighing (physiological sigh)',
    category: 'breath',
    claim:
      'A double-inhale followed by a long exhale outperforms equal-time box breathing and mindfulness for acute mood and respiratory rate reduction.',
    evidenceLevel: 'strong',
    citation: {
      authors: 'Balban MY, Neri E, Kogon MM et al.',
      year: 2023,
      title:
        'Brief structured respiration practices enhance mood and reduce physiological arousal',
      journal: 'Cell Reports Medicine, 4(1), 100895',
      doi: 'https://doi.org/10.1016/j.xcrm.2022.100895',
    },
    mechanism:
      'The double-inhale fully expands collapsed alveoli, allowing the prolonged exhale to off-load more CO₂ and engage stronger vagal braking than single-cycle breathwork.',
    effectSize:
      '5 min/day × 28 days, RCT (n = 114): cyclic sighing produced larger improvements in daily mood and greater reduction in 24-h respiratory rate than box breathing or mindfulness meditation.',
  },
  {
    id: 'hrv-resilience-biomarker',
    technique: 'HRV as a recovery biomarker',
    category: 'nervous_system',
    claim:
      'Vagally-mediated HRV indexes autonomic flexibility, self-regulation, and resilience.',
    evidenceLevel: 'strong',
    citation: {
      authors: 'Shaffer F, Ginsberg JP',
      year: 2017,
      title: 'An Overview of Heart Rate Variability Metrics and Norms',
      journal: 'Frontiers in Public Health, 5, 258',
      doi: 'https://doi.org/10.3389/fpubh.2017.00258',
    },
    mechanism:
      'Vagally-mediated HRV (RMSSD, HF) reflects the parasympathetic brake on the heart, generated by a prefrontal–amygdala–vagal network. Higher resting vagal HRV maps to better executive function and emotional regulation.',
    effectSize:
      'Canonical reference establishing normative HRV across short-term and 24-hour recordings. "An optimal level of HRV is associated with health and self-regulatory capacity."',
  },
  {
    id: 'vagal-slow-exhale',
    technique: 'Vagal activation via slow exhalation',
    category: 'nervous_system',
    claim:
      'Lengthening the exhale relative to the inhale stimulates the vagus nerve and deepens parasympathetic engagement.',
    evidenceLevel: 'strong',
    citation: {
      authors: 'Gerritsen RJS, Band GPH',
      year: 2018,
      title:
        'Breath of Life: The Respiratory Vagal Stimulation Model of Contemplative Activity',
      journal: 'Frontiers in Human Neuroscience, 12, 397',
      doi: 'https://doi.org/10.3389/fnhum.2018.00397',
    },
    mechanism:
      'Vagal cardiac efferents are gated by the respiratory cycle — facilitated on exhale, suppressed on inhale. Slow paced breathing with prolonged exhale increases vagal tone, which feeds back to the CNS via afferents.',
    effectSize:
      'Mechanistic review: slow breathing with prolonged exhale reliably increases RMSSD and HF power and reduces sympathetic markers across the contemplative practice literature.',
  },
  {
    id: 'pfc-stress-depletion',
    technique: 'Prefrontal cortex impairment under stress',
    category: 'nervous_system',
    claim:
      'Sustained stress impairs prefrontal cortex function and degrades decision quality.',
    evidenceLevel: 'strong',
    citation: {
      authors: 'Arnsten AFT',
      year: 2009,
      title:
        'Stress signalling pathways that impair prefrontal cortex structure and function',
      journal: 'Nature Reviews Neuroscience, 10(6), 410–422',
      doi: 'https://doi.org/10.1038/nrn2648',
    },
    mechanism:
      'Acute stress drives catecholamine release in PFC that weakens local network connections while strengthening amygdala/basal-ganglia circuits, shifting behaviour from reflective to reflexive. Chronic stress drives dendritic atrophy.',
    effectSize:
      'Canonical mechanistic review of how stress disconnects the executive system from cognitive control.',
  },
  {
    id: 'pascoe-meditation-cortisol',
    technique: 'Body scan / mindfulness and cortisol',
    category: 'mind',
    claim:
      'Focused-attention meditation, including body scan, reduces circulating cortisol and other stress markers.',
    evidenceLevel: 'moderate',
    citation: {
      authors: 'Pascoe MC, Thompson DR, Jenkins ZM, Ski CF',
      year: 2017,
      title:
        'Mindfulness mediates the physiological markers of stress: Systematic review and meta-analysis',
      journal: 'Journal of Psychiatric Research, 95, 156–178',
      doi: 'https://doi.org/10.1016/j.jpsychires.2017.08.004',
    },
    mechanism:
      'Meditation attenuates HPA-axis output, reducing circulating cortisol, blood pressure, heart rate, and inflammatory markers (TNF-α, CRP) compared to active controls.',
    effectSize:
      'Across 45 RCTs, focused-attention meditation significantly reduced cortisol vs active controls. A specific "25% reduction" figure circulating in wellness writing is NOT supported by this paper — direction yes, magnitude varies by protocol.',
  },
  {
    id: 'implementation-intentions',
    technique: 'Implementation intentions',
    category: 'mind',
    claim:
      'A specific if-then intention activates executive function and increases follow-through.',
    evidenceLevel: 'strong',
    citation: {
      authors: 'Gollwitzer PM, Sheeran P',
      year: 2006,
      title:
        'Implementation intentions and goal achievement: A meta-analysis of effects and processes',
      journal: 'Advances in Experimental Social Psychology, 38, 69–119',
      doi: 'https://doi.org/10.1016/S0065-2601(06)38002-1',
    },
    mechanism:
      'If-then plans delegate action initiation from effortful top-down control to a pre-specified situational cue, freeing executive resources and automating goal pursuit.',
    effectSize:
      'Meta-analysis of 94 independent tests: medium-to-large effect on goal attainment (d = 0.65) over and above mere goal intentions.',
  },
  {
    id: 'ultradian-deliberate-practice',
    technique: '60–90 minute focused work blocks',
    category: 'mind',
    claim:
      'Elite performers work in concentrated 60–90 minute blocks before requiring deliberate rest.',
    evidenceLevel: 'emerging',
    citation: {
      authors: 'Ericsson KA, Krampe RT, Tesch-Römer C',
      year: 1993,
      title:
        'The role of deliberate practice in the acquisition of expert performance',
      journal: 'Psychological Review, 100(3), 363–406',
      doi: 'https://doi.org/10.1037/0033-295X.100.3.363',
    },
    mechanism:
      'Sustained full-concentration practice has diminishing returns past roughly 60–90 minutes. Recovery between blocks restores capacity; daily total deliberate-practice load plateaus near 4–5 hours.',
    effectSize:
      'Top violinists practised in ~80–90 min sessions with explicit rest. The strict 90-minute biological "BRAC" cycle remains contested; the deliberate-practice block pattern is the strongest defensible framing.',
  },
  {
    id: 'nsdr-dopamine',
    technique: 'NSDR / Yoga Nidra and dopamine',
    category: 'recovery',
    claim:
      'Yoga nidra (non-sleep deep rest) increased endogenous dopamine release in a small PET study.',
    evidenceLevel: 'emerging',
    citation: {
      authors: 'Kjaer TW, Bertelsen C, Piccini P, Brooks D, Alving J, Lou HC',
      year: 2002,
      title:
        'Increased dopamine tone during meditation-induced change of consciousness',
      journal: 'Cognitive Brain Research, 13(2), 255–259',
      doi: 'https://doi.org/10.1016/S0926-6410(01)00106-9',
    },
    mechanism:
      '11C-raclopride PET imaging showed reduced raclopride binding in ventral striatum during yoga nidra — indicating greater endogenous dopamine occupancy of D2 receptors.',
    effectSize:
      '7.9% decrease in 11C-raclopride binding ≈ ~65% increase in endogenous dopamine release. n = 8 experienced practitioners. Single small study; not independently replicated with PET.',
  },
  {
    id: 'worry-postponement',
    technique: 'Deferred future-focused worry',
    category: 'recovery',
    claim:
      'Postponing future-focused worry reduces daily worry frequency and may shorten the cardiovascular tail of stress.',
    evidenceLevel: 'emerging',
    citation: {
      authors: 'Brosschot JF, Gerin W, Thayer JF',
      year: 2006,
      title:
        'The perseverative cognition hypothesis: A review of worry, prolonged stress-related physiological activation, and health',
      journal: 'Journal of Psychosomatic Research, 60(2), 113–124',
      doi: 'https://doi.org/10.1016/j.jpsychores.2005.06.074',
    },
    mechanism:
      'Worry and rumination ("perseverative cognition") prolong cardiovascular, endocrine, and HPA activation before and after stressors. Interrupting forward-projection can shorten this tail.',
    effectSize:
      'Narrative review + RCTs (Borkovec et al.) show worry-postponement reduces daily worry frequency. A direct cortisol effect of "set tomorrow down" framing has not been measured.',
  },
  {
    id: 'cycle-mcnulty-meta',
    technique: 'Menstrual cycle and exercise performance',
    category: 'cycle',
    claim:
      'Group-level performance differences across cycle phases are trivial; individual variation is large.',
    evidenceLevel: 'moderate',
    citation: {
      authors:
        'McNulty KL, Elliott-Sale KJ, Dolan E, Swinton PA, Ansdell P, Goodall S, Thomas K, Hicks KM',
      year: 2020,
      title:
        'The Effects of Menstrual Cycle Phase on Exercise Performance in Eumenorrheic Women: A Systematic Review and Meta-Analysis',
      journal: 'Sports Medicine, 50(10), 1813–1827',
      doi: 'https://doi.org/10.1007/s40279-020-01319-3',
    },
    mechanism:
      'Sex-hormone fluctuations alter thermoregulation, substrate use, neuromuscular control, and recovery markers, but inter-individual variation is large.',
    effectSize:
      'Across 78 studies, performance was "trivially reduced" in early follicular vs other phases (SMD ≈ −0.06). The authors recommend personalised, not phase-prescriptive, programming.',
  },
  {
    id: 'cycle-follicular-cognition',
    technique: 'Estrogen and learning windows',
    category: 'cycle',
    claim:
      'Rising estradiol in the late follicular phase is associated with hippocampal volume increase and improvements in verbal and working memory.',
    evidenceLevel: 'moderate',
    citation: {
      authors: 'Barth C, Villringer A, Sacher J',
      year: 2015,
      title:
        'Sex hormones affect neurotransmitters and shape the adult female brain during hormonal transition periods',
      journal: 'Frontiers in Neuroscience, 9, 37',
      doi: 'https://doi.org/10.3389/fnins.2015.00037',
    },
    mechanism:
      'Estradiol enhances hippocampal spine density, glutamatergic transmission, and BDNF expression while moderating GABAergic inhibition.',
    effectSize:
      'Imaging studies show measurable hippocampal volume increase during high-estrogen phases; cognitive gains are modest at the group level.',
  },
  {
    id: 'cycle-luteal',
    technique: 'Luteal phase and perceived effort',
    category: 'cycle',
    claim:
      'Premenstrual / late-luteal symptoms — fatigue, sleep disturbance, raised perceived effort — affect many but not all menstruating people.',
    evidenceLevel: 'moderate',
    citation: {
      authors: 'Carmichael MA, Thomson RL, Moran LJ, Wycherley TP',
      year: 2021,
      title:
        "The Impact of Menstrual Cycle Phase on Athletes' Performance: A Narrative Review",
      journal:
        'International Journal of Environmental Research and Public Health, 18(4), 1667',
      doi: 'https://doi.org/10.3390/ijerph18041667',
    },
    mechanism:
      'Elevated progesterone raises basal body temperature, ventilation, and perceived exertion. Premenstrual fatigue and mood disturbance are well-documented but vary by individual.',
    effectSize:
      'PMS affects up to ~90% of menstruating women in some form; late-luteal wellness scores are consistently lower than mid-cycle in athlete cohorts.',
  },
  {
    id: 'cycle-methodology',
    technique: 'Cycle-aware programming, done responsibly',
    category: 'cycle',
    claim:
      'Track individual response over time; do not prescribe rigid phase rules.',
    evidenceLevel: 'strong',
    citation: {
      authors:
        'Elliott-Sale KJ, Minahan CL, de Jonge XAKJ, Ackerman KE et al.',
      year: 2021,
      title:
        'Methodological Considerations for Studies in Sport and Exercise Science with Women as Participants',
      journal: 'Sports Medicine, 51(5), 843–861',
      doi: 'https://doi.org/10.1007/s40279-021-01435-8',
    },
    mechanism:
      'Sex-specific endocrine fluctuations affect physiology, but the field\'s evidence base is methodologically weak. Programming should track individual response rather than enforce phase rules.',
    effectSize:
      'Position paper: phase-prescriptive programming is not yet supported. Individualised cycle tracking with biomarker confirmation is the recommended approach.',
  },
] as const);

export const CATEGORY_LABEL: Record<Evidence['category'], string> = {
  breath: 'Breath',
  nervous_system: 'Nervous System',
  mind: 'Mind',
  cycle: 'Cycle',
  recovery: 'Recovery',
};

export const EVIDENCE_LEVEL_LABEL: Record<EvidenceLevel, string> = {
  strong: 'Strong evidence',
  moderate: 'Moderate evidence',
  emerging: 'Emerging evidence',
};

export const EVIDENCE_LEVEL_COLOR: Record<EvidenceLevel, string> = {
  strong: '#7AD27A',
  moderate: '#C9A53C',
  emerging: '#A09880',
};

export function getEvidence(id: string): Evidence | undefined {
  return EVIDENCE.find((e) => e.id === id);
}

// Map session steps and cycle phases to their primary citations.
export const STEP_CITATIONS: Record<string, string[]> = {
  'stolen-body': ['vagal-slow-exhale'],
  'stolen-energy': ['breathing-4-7-8', 'vagal-slow-exhale', 'physiological-sigh'],
  'stolen-mind': ['pfc-stress-depletion', 'implementation-intentions'],
  'stolen-soul': ['implementation-intentions', 'ultradian-deliberate-practice'],
  'winddown-body': ['resonant-breathing-6bpm', 'vagal-slow-exhale'],
  'winddown-energy': ['pascoe-meditation-cortisol'],
  'winddown-mind': ['implementation-intentions'],
  'winddown-soul': ['worry-postponement'],
};

export const PHASE_CITATIONS: Record<string, string[]> = {
  menstrual: ['cycle-mcnulty-meta', 'cycle-methodology'],
  follicular: ['cycle-follicular-cognition'],
  ovulatory: ['cycle-mcnulty-meta'],
  luteal: ['cycle-luteal'],
};
